# Generated by Django 4.1.7 on 2023-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.AddField(
            model_name="song",
            name="albums",
            field=models.ManyToManyField(related_name="songs", to="music.album"),
        ),
    ]
