# Generated by Django 4.1.7 on 2023-02-19 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_remove_song_album_song_albums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="albums",
        ),
        migrations.RemoveField(
            model_name="song",
            name="position",
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "album",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.song"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
