# Generated by Django 4.1.7 on 2023-02-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_remove_song_albums_remove_song_position_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.album"
            ),
        ),
    ]
