# Generated by Django 4.1.7 on 2023-02-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_alter_position_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.song"
            ),
        ),
    ]
