# Generated by Django 4.1.7 on 2023-02-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_album_songs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Position",
            new_name="AlbumSong",
        ),
    ]
